language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  
before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev
    - mkdir -p build/logs

script: 
    - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
    
after_success:
    - travis_retry php vendor/bin/coveralls -v
  